# Generated by Django 3.2.3 on 2021-05-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('firstName', models.CharField(max_length=256)),
                ('currentTeam', models.CharField(max_length=256)),
                ('attendance', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=256)),
                ('id_utilisateur', models.ManyToManyField(blank=True, related_name='teams', to='Equipes.Utilisateur')),
            ],
        ),
    ]
