# Generated by Django 3.2.3 on 2021-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id_utilisateur',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='id_utilisateur',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='Equipes.Team'),
        ),
    ]
