# Generated by Django 3.2.3 on 2021-05-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0002_auto_20210526_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='id_utilisateur',
        ),
        migrations.AddField(
            model_name='team',
            name='id_utilisateur',
            field=models.ManyToManyField(blank=True, related_name='teams', to='Equipes.Utilisateur'),
        ),
    ]
