# Generated by Django 3.2.3 on 2021-05-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0004_rename_id_utilisateur_team_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=256)),
                ('firstName', models.CharField(max_length=256)),
                ('heigth', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('VMA', models.IntegerField()),
                ('placeOnField', models.CharField(max_length=256)),
                ('globalScore', models.IntegerField()),
                ('id_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipes.team')),
            ],
        ),
    ]
