# Generated by Django 3.2.3 on 2021-05-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0008_auto_20210526_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='utilisateur',
            field=models.ManyToManyField(blank=True, related_name='team', to='Equipes.Utilisateur'),
        ),
    ]
