# Generated by Django 3.2.3 on 2021-05-28 09:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Equipes', '0009_alter_team_utilisateur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateur',
            new_name='UserInformations',
        ),
    ]
