# Generated by Django 3.2.3 on 2021-05-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0011_auto_20210528_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.DeleteModel(
            name='CoachParams',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
