# Generated by Django 3.2.3 on 2021-05-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0014_auto_20210528_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachparams',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='coachParams', to='Equipes.Team'),
        ),
    ]
