# Generated by Django 3.2.3 on 2021-05-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0016_rename_user_coachparams_userr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachparams',
            old_name='userr',
            new_name='user',
        ),
    ]
