# Generated by Django 3.2.3 on 2021-05-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0017_rename_userr_coachparams_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('game', models.ManyToManyField(blank=True, related_name='player', to='Equipes.Player')),
            ],
        ),
    ]
