# Generated by Django 3.2.3 on 2021-05-29 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0019_auto_20210529_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameGame', models.CharField(max_length=255)),
                ('numberGroups', models.IntegerField()),
                ('dateGame', models.DateField(auto_now_add=True)),
                ('completed', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Equipes.game'),
            preserve_default=False,
        ),
    ]
