# Generated by Django 3.2.3 on 2021-05-29 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0020_auto_20210529_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameGame', models.CharField(max_length=255)),
                ('offLineYes', models.BooleanField(default=False)),
                ('offLineNo', models.BooleanField(default=False)),
                ('goalKeeperYes', models.BooleanField(default=False)),
                ('goalKeeperNo', models.BooleanField(default=False)),
                ('synthetiqueDry', models.BooleanField(default=False)),
                ('synthetiqueWet', models.BooleanField(default=False)),
                ('stabiliseDry', models.BooleanField(default=False)),
                ('stabiliseWet', models.BooleanField(default=False)),
                ('grassDry', models.BooleanField(default=False)),
                ('grassWet', models.BooleanField(default=False)),
                ('otherField', models.BooleanField(default=False)),
                ('goal11', models.BooleanField(default=False)),
                ('goal7', models.BooleanField(default=False)),
                ('goalEmbut', models.BooleanField(default=False)),
                ('goalNone', models.BooleanField(default=False)),
                ('goalOther', models.BooleanField(default=False)),
                ('TB1_3', models.BooleanField(default=False)),
                ('TB_2', models.BooleanField(default=False)),
                ('TB_free', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='gameModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Equipes.gamemodel'),
        ),
    ]
