# Generated by Django 3.2.3 on 2021-05-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0021_auto_20210529_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='goalSmall',
            field=models.BooleanField(default=False),
        ),
    ]
