# Generated by Django 3.2.3 on 2021-05-31 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0022_gamemodel_goalsmall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='gameModel',
        ),
        migrations.AddField(
            model_name='game',
            name='gameModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Equipes.gamemodel'),
        ),
    ]
