# Generated by Django 3.2.3 on 2021-06-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0024_auto_20210531_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemodel',
            old_name='model',
            new_name='game',
        ),
    ]
