# Generated by Django 3.2.3 on 2021-06-13 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0026_auto_20210602_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='DimensionGrand',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='DimensionMoyen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='DimensionPetit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
