# Generated by Django 3.2.3 on 2021-06-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0027_auto_20210613_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='DimensionGrand',
            field=models.BooleanField(default=False),
        ),
    ]
