# Generated by Django 3.2.3 on 2021-06-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0028_alter_gamemodel_dimensiongrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachparams',
            name='fenetre',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='coachparams',
            name='nbMatch',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='coachparams',
            name='tolerance',
            field=models.IntegerField(default=1),
        ),
    ]
