# Generated by Django 3.2.3 on 2021-06-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipes', '0029_auto_20210619_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachparams',
            name='fenetre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coachparams',
            name='nbMatch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coachparams',
            name='tolerance',
            field=models.IntegerField(),
        ),
    ]
